### ISSUE TITLE
Login Authentication Failure

### ISSUE THREAD

**Issue by cncoder** [aws-samples/bedrock-claude-codecoach#14]
The login process for the Code Coach application is failing with the error message "SignIn information: auth failed!". This issue is preventing users from signing in to their accounts. Further investigation revealed the following error in the application logs:

```
QuerySignUsers invoke
ResourceNotFoundException: Requested resource not found
    at _ (/app/.next/server/chunks/2.js:1:19060)
    at A (/app/.next/server/chunks/2.js:1:17223)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/.next/server/chunks/179.js:30:31951
    at async /app/.next/server/chunks/179.js:30:2436
    at async /app/.next/server/chunks/179.js:30:30832
    at async /app/.next/server/chunks/179.js:21:4301
    at async x (/app/.next/server/app/api/signin/route.js:1:3010)
    at async d (/app/.next/server/app/api/signin/route.js:1:1246)
    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41960 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'MR3I41SQM3VT2UR6JBF8HBLS5VVV4KQNSO5AEMVJF66Q9ASUAAJG',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazonaws.dynamodb.v20120810#ResourceNotFoundException'
```

Steps to Reproduce:

Navigate to the Code Coach application login page.
Enter a valid email address (e.g., [admin@demo.com](mailto:admin@demo.com)) and password.
Click the "Sign in" button.
The application displays the error message "SignIn information: auth failed!" and does not proceed with the login.
Additional Information:

The application is running in Docker containers, as shown in the provided terminal output.
The Docker containers are named "codecoach" and "piston_api".
During the startup of the "codecoach" container, there are warnings about the "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY" environment variables not being set, which may be related to the authentication issue.

![image](https://github.com/aws-samples/bedrock-claude-codecoach/assets/11889736/1dbb71f0-51c2-48a5-b62e-03c6ec09b901)

![image](https://github.com/aws-samples/bedrock-claude-codecoach/assets/11889736/c28427b2-0f90-4cc7-97ae-2404b81c6916)

![image](https://github.com/aws-samples/bedrock-claude-codecoach/assets/11889736/81d23908-2a3a-46be-b302-d3567d7e9340)

![image](https://github.com/aws-samples/bedrock-claude-codecoach/assets/11889736/b0e25126-be9a-44d9-94cd-5b7f6c6e0d9b)

**Comment by cncoder** [comment]
The issue might be caused by a mismatch between the AWS region where the application is deployed (us-east-1) and the hardcoded AWS region in the [.env.local](https://github.com/aws-samples/bedrock-claude-codecoach/blob/main/.env.local)
file (us-west-2). This region mismatch could be preventing the application from finding the required DynamoDB table, leading to the ResourceNotFoundException.
